---
- name: Destroy
  hosts: localhost
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"

  tasks:
    - name: Add SmartOS host to inventory
      add_host:
        name: smartos-host

    - name: Destroy instances
      vmadm:
        alias: "{{ item.name }}"
        state: absent
      delegate_to: smartos-host
      loop: "{{ molecule_yml.platforms }}"
