---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mariadb-alpine-3.7
    image: alpine:3.7
    volumes:
      - "/mnt/mirrors/alpine/3.7:/var/cache/apk"
    privileged: true
    command: /sbin/init
  - name: mariadb-alpine-3.8
    image: alpine:3.8
    volumes:
      - "/mnt/mirrors/alpine/3.8:/var/cache/apk"
    privileged: true
    command: /sbin/init
  - name: mariadb-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
    privileged: true
    command: sleep infinity
  - name: mariadb-debian-testing
    image: debian:testing
    volumes:
      - "/mnt/mirrors/debian/testing:/var/cache/apt/archives"
    privileged: true
    command: sleep infinity
  - name: mariadb-ubuntu-16.04
    image: ubuntu:16.04
    volumes:
      - "/mnt/mirrors/ubuntu/16.04:/var/cache/apt/archives"
    privileged: true
    command: sleep infinity
  - name: mariadb-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
    privileged: true
    command: sleep infinity
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
