---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mariadb-alpine-3.7
    image: alpine:3.7
    volumes:
      - "/mnt/mirrors/alpine/3.7:/var/cache/apk"
    privileged: true
    command: /sbin/init
  - name: mariadb-alpine-3.8
    image: alpine:3.8
    volumes:
      - "/mnt/mirrors/alpine/3.8:/var/cache/apk"
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
