---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: mariadb-alpine-3.9
    image: alpine:3.9
    volumes:
      - "/mnt/mirrors/alpine/3.9:/var/cache/apk"
    command: /sbin/init
  - name: mariadb-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
    command: /lib/systemd/systemd
  - name: mariadb-ubuntu-16.04
    image: ubuntu:16.04
    volumes:
      - "/mnt/mirrors/ubuntu/16.04:/var/cache/apt/archives"
    command: /sbin/init
  - name: mariadb-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
    command: /sbin/init
  - name: mariadb-ubuntu-20.04
    image: ubuntu:20.04
    volumes:
      - "/mnt/mirrors/ubuntu/20.04:/var/cache/apt/archives"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  # log: true
  config_options:
    defaults:
      interpreter_python: "/usr/bin/python3"
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
scenario:
  name: default
