---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: mariadb-alpine-3.8
    image: alpine:3.8
    volumes:
      - "/mnt/mirrors/alpine/3.8:/var/cache/apk"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: mariadb-alpine-3.9
    image: alpine:3.9
    volumes:
      - "/mnt/mirrors/alpine/3.9:/var/cache/apk"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: mariadb-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /bin/systemd
  - name: mariadb-debian-testing
    image: debian:testing
    volumes:
      - "/mnt/mirrors/debian/testing:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      - /var/run
    capabilities:
      - SYS_ADMIN
    privileged: true
    command: /sbin/init
  - name: mariadb-ubuntu-16.04
    image: ubuntu:16.04
    volumes:
      - "/mnt/mirrors/ubuntu/16.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: mariadb-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
provisioner:
  name: ansible
  # log: true
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
scenario:
  name: default
